### ISSUE TITLE
Tracking Issue: Adding mdbook-spec identifiers to reference chapters

### ISSUE THREAD

**Issue by chorman0773** [rust-lang/reference#1561]
From #1550: 
> The go forward plan adopted by T-spec on 2024-06-13 includes, as one step, to reformat all of the chapters of the Reference to attach named identifiers to each claim, more or less. 

This issue tracks the status of each chapter of the reference being updated in this manner, in alphabetical order.

- [ ] abi.md (Resolve status of currently open PRs)
- [ ] attributes.md (Open #1560)
    - [ ] attributes/codegen.md (Open #1560)
    - [ ] attributes/debugger.md (Open #1560)
    - [ ] attributes/derive.md (Open #1560)
    - [ ] attributes/diagnostics.md (Open #1560)
    - [ ] attributes/limits.md (Open #1560)
    - [ ] attributes/testing.md (Open #1560)
    - [ ] attributes/type_system.md (Open #1560)
- [ ] behaviour-considered-undefined.md
- [ ] behaviour-not-considered-unsafe.md
- [ ] comments.md
- [ ] conditional-compliation.md
- [ ] const_eval.md
- [ ] crates-and-source-files.md
- [ ] destructors.md
- [ ] dynamically-sized-types.md
- [ ] expressions.md
    - [ ] expressions/array-expr.md
    - [ ] expressions/await-expr.md
    - [ ] expressions/block-expr.md
    - [ ] expressions/call-expr.md
    - [ ] expressions/closure-expr.md
    - [ ] expressions/field-expr.md
    - [ ] expressions/grouped-expr.md
    - [ ] expressions/if-expr.md
    - [ ] expressions/literal-expr.md
    - [ ] expressions/loop-expr.md
    - [ ] expressions/match-expr.md
    - [ ] expressions/method-call-expr.md
    - [ ] expressions/operator-expr.md
    - [ ] expressions/path-expr.md
    - [ ] expressions/range-expr.md
    - [ ] expressions/return-expr.md
    - [ ] expressions/struct-expr.md
    - [ ] expressions/tuple-expr.md
    - [ ] expressions/underscore-expr.md
- [ ] glossary.md
- [ ] identifiers.md
- [ ] inline-assembly.md (Open #1550)
- [ ] input-format.md
- [ ] interior-mutability.md
- [ ] items.md
- [ ] keywords.md
- [ ] lexical-structure.md
- [ ] lifetime-elision.md
- [ ] linkage.md
- [ ] macro-ambiguity.md
- [ ] macros-by-example.md
- [ ] macros.md
- [ ] memory-allocation-and-lifetimes.md
- [ ] names.md
- [ ] notation.md
- [ ] paths.md
- [ ] patterns.md
- [ ] procedural-macros.md
- [ ] runtime.md
- [ ] special-types-and-traits.md
- [ ] statements.md
- [ ] statements-and-expressions.md
- [ ] subtyping,md
- [ ] tokens.md
- [ ] trait-bounds.md
- [ ] type-coercions.md
- [ ] type-layout.md
- [ ] type-system.md
- [ ] types.md
    - [ ] types/array.md
    - [ ] types/boolean.md
    - [ ] types/closure/md
    - [ ] types/enum.md
    - [ ] types/function-item.md
    - [ ] types/function-pointer.md
    - [ ] types/impl-trait.md
    - [ ] types/inferred.md
    - [ ] types/never.md
    - [ ] types/numeric.md
    - [ ] types/parameter.md
    - [ ] types/pointer.md
    - [ ] types/slice.md
    - [ ] types/struct.md
    - [ ] types/textual.md
    - [ ] types/trait-object.md
    - [ ] types/tuple.md
    - [ ] types/union.md
- [ ] unsafe-keyword.md
- [ ] unsafety.md
- [ ] variables.md
- [ ] visibility-and-privacy.md
- [ ] whitespace.md
